# Deployment manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-manager
  template:
    metadata:
      labels:
        app: receipt-manager
    spec:
      containers:
        - image: zgtodoappregistry.azurecr.io/receipt-manager:latest
          name: receipt-manager
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: receipt-manager-secrets
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: receipt-manager-secrets
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: receipt-manager-secrets
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: name
                  name: receipt-manager-secrets
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mail_username
                  name: receipt-manager-secrets
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mail_password
                  name: receipt-manager-secrets
            - name: MAIL_FROM
              valueFrom:
                secretKeyRef:
                  key: mail_from
                  name: receipt-manager-secrets
            - name: MAIL_PORT
              valueFrom:
                secretKeyRef:
                  key: mail_port
                  name: receipt-manager-secrets
            - name: MAIL_SERVER
              valueFrom:
                secretKeyRef:
                  key: mail_server
                  name: receipt-manager-secrets
            - name: MAIL_TLS
              valueFrom:
                secretKeyRef:
                  key: mail_tls
                  name: receipt-manager-secrets
            - name: MAIL_SSL
              valueFrom:
                secretKeyRef:
                  key: mail_ssl
                  name: receipt-manager-secrets
            - name: USE_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: use_credentials
                  name: receipt-manager-secrets
            # - name: EXTERNAL_IP
            #   valueFrom:
            #     secretKeyRef:
            #       key: external_ip
            #       name: receipt-manager-secrets
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - receipt-manager
              topologyKey: "kubernetes.io/hostname"
---
# Service manifest
apiVersion: v1
kind: Service
metadata:
  name: receiptmanager-server
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: receipt-manager
