version: "3.9"
services:
  web:
    build: ./app
    restart: always
    volumes:
      - "./app:/usr/src/app"
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build: ./app/nginx
    volumes:
      - "${PWD}:/etc/nginx/templates"
    ports:
      - 8080:80
    depends_on:
      - web
      - db

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: receipt-manager
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "${PWD}:/app/todo-app/psql"

  #[For tests]
  db-test:
    image: postgres:14-alpine
    restart: always
    container_name: test-db
    environment:
      POSTGRES_DB: test-db
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - 5433:5432
  # [docker exec -it [container_name] psql -U [username] -W [db_name]]
