branch-defaults:
  main:
    environment: receipt-manager-env
    group_suffix: null
environment-defaults:
  todo-app-env:
    branch: null
    repository: null
global:
  application_name: Receipt Manager
  branch: null
  default_ec2_keyname: primary
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
